#! /bin/sh

#running the python script first
#it will generate letters, add those letters to the file text.txt
#file gonna change and git will see those changes

python3 rand_gen.py

#executing classic git commands
#and since we have added and bind ssh key to the VPS system 
#we can automatically upload git changes to the remote repo
#without any logins or passwords

git add .
git commit -m "autogenerated by script"
git push --force
